# Generated by Django 3.1.3 on 2021-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.CharField(max_length=100)),
                ('ReportedDateTime', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Symbol', models.CharField(max_length=100)),
                ('InsiderRelationship', models.CharField(max_length=100)),
                ('SharesTraded', models.CharField(max_length=100)),
                ('AveragePrice', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=100)),
                ('SharesOwned', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(verbose_name='작성일'),
        ),
    ]
