# Generated by Django 3.1.3 on 2021-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='AveragePrice',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='InsiderRelationship',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='ReportedDateTime',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='SharesOwned',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='SharesTraded',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Symbol',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='TransactionDate',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='Type',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
