# Generated by Django 3.1.3 on 2021-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_clusterinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterinfo',
            name='AveragePrice',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='InsiderRelationship',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='ReportedDateTime',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='SharesOwned',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='SharesTraded',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='Symbol',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='TransactionDate',
        ),
        migrations.RemoveField(
            model_name='clusterinfo',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='FilingDate',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='FilingTime',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Industry',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Owned',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Ticker',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='TradeDate',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='TradeType',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='Value',
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='CompanyName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='FilingDate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='FilingTime',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Industry',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Owned',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Qty',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Ticker',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='TradeDate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='TradeType',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterinfo',
            name='Value',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='AveragePrice',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='Company',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='InsiderRelationship',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='ReportedDateTime',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='SharesOwned',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='SharesTraded',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='Symbol',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='TotalAmount',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='TransactionDate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='Type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
