# Generated by Django 3.1.3 on 2021-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20210506_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilingDate', models.TextField()),
                ('FilingTime', models.TextField()),
                ('TradeDate', models.TextField()),
                ('Ticker', models.TextField()),
                ('CompanyName', models.TextField()),
                ('Industry', models.TextField()),
                ('TradeType', models.TextField()),
                ('Price', models.TextField()),
                ('Qty', models.TextField()),
                ('Owned', models.TextField()),
                ('Value', models.TextField()),
            ],
        ),
    ]
