# Generated by Django 3.1.3 on 2021-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusterinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.TextField()),
                ('ReportedDateTime', models.TextField()),
                ('Company', models.TextField()),
                ('Symbol', models.TextField()),
                ('InsiderRelationship', models.TextField()),
                ('SharesTraded', models.TextField()),
                ('AveragePrice', models.TextField()),
                ('TotalAmount', models.TextField()),
                ('SharesOwned', models.TextField()),
                ('Type', models.TextField()),
            ],
        ),
    ]
